### ISSUE TITLE
new lsl issue

### ISSUE THREAD

**Issue by pratiksan** [lwa-project/pulsar#4]
running the following return the error below, /usr/local/extensions/Pulsar/drx2drxi.py filename
looks like something needs changing in buffer.py or maybe some import method in drx2drxi.py.

Traceback (most recent call last):
  File "/usr/local/extensions/Pulsar/drx2drxi.py", line 402, in <module>
    main(args)
  File "/usr/local/extensions/Pulsar/drx2drxi.py", line 272, in main
    rFrames = buffer.get()
  File "/usr/local/lib/python2.7/dist-packages/lsl/reader/buffer.py", line 321, in get
    output.extend( map(lambda x: self.create_fill(key_to_return, x), self._get_missing_list(key_to_return)) )
  File "/usr/local/lib/python2.7/dist-packages/lsl/reader/buffer.py", line 321, in <lambda>
    output.extend( map(lambda x: self.create_fill(key_to_return, x), self._get_missing_list(key_to_return)) )
  File "/usr/local/lib/python2.7/dist-packages/lsl/reader/buffer.py", line 228, in create_fill
    raise NotImplementedError
NotImplementedError

**Comment by jaycedowell** [comment]
Yeah, looks like `RawDRXFrameBuffer` needed to be updated.  Try it now.
